// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKED5r_n07QnXNmHxP4xWuj6uIMU2F3OM',
    appId: '1:533526268311:web:86d0e404749600d74a1cd2',
    messagingSenderId: '533526268311',
    projectId: 'ozses-11cb2',
    authDomain: 'ozses-11cb2.firebaseapp.com',
    storageBucket: 'ozses-11cb2.firebasestorage.app',
    measurementId: 'G-2JPZQDKBCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH038IbGRqmbIgcuJuxM-SFJ6wsqyIFj8',
    appId: '1:533526268311:android:641e182c5a2c733d4a1cd2',
    messagingSenderId: '533526268311',
    projectId: 'ozses-11cb2',
    storageBucket: 'ozses-11cb2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpoo9IvQaL4M9QHJlTUMMVv6ra83Zn7Y',
    appId: '1:533526268311:ios:25f1ce60c339864a4a1cd2',
    messagingSenderId: '533526268311',
    projectId: 'ozses-11cb2',
    storageBucket: 'ozses-11cb2.firebasestorage.app',
    iosClientId: '533526268311-tcv8k1qdb944innirdg595jqk7tdr9og.apps.googleusercontent.com',
    iosBundleId: 'com.example.ozsesV7Imperium',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpoo9IvQaL4M9QHJlTUMMVv6ra83Zn7Y',
    appId: '1:533526268311:ios:25f1ce60c339864a4a1cd2',
    messagingSenderId: '533526268311',
    projectId: 'ozses-11cb2',
    storageBucket: 'ozses-11cb2.firebasestorage.app',
    iosClientId: '533526268311-tcv8k1qdb944innirdg595jqk7tdr9og.apps.googleusercontent.com',
    iosBundleId: 'com.example.ozsesV7Imperium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKED5r_n07QnXNmHxP4xWuj6uIMU2F3OM',
    appId: '1:533526268311:web:e8e5127959e392a34a1cd2',
    messagingSenderId: '533526268311',
    projectId: 'ozses-11cb2',
    authDomain: 'ozses-11cb2.firebaseapp.com',
    storageBucket: 'ozses-11cb2.firebasestorage.app',
    measurementId: 'G-9VM8P12LTM',
  );
}
